import React, { useEffect, useState } from "react";
import { toast } from "sonner";
import axios from "axios";
import { ChevronDown, Mail, Trash2, Check, DollarSign, Users, Flame, Copy } from "lucide-react";

const STATUS_OPTIONS = [
  { id: "new", label: "New Lead", tone: "amber" },
  { id: "contacted", label: "Contacted", tone: "blue" },
  { id: "quoted", label: "Quoted", tone: "default" },
  { id: "booked", label: "Booked", tone: "green" },
  { id: "cancelled", label: "Cancelled", tone: "red" },
];

function statusTone(id) {
  return STATUS_OPTIONS.find((s) => s.id === id)?.tone || "gray";
}

function Badge({ children, tone = "default" }) {
  const tones = {
    default: "border-[#C8A96A]/40 text-[#C8A96A]",
    green: "border-emerald-600/60 text-emerald-400",
    red: "border-red-500/60 text-red-300",
    blue: "border-sky-500/60 text-sky-300",
    gray: "border-[#A89F8F]/30 text-[#A89F8F]",
    amber: "border-amber-500/60 text-amber-300",
  };
  return (
    <span className={`inline-flex items-center text-[0.65rem] uppercase tracking-[0.22em] px-2 py-1 border ${tones[tone] || tones.default}`}>
      {children}
    </span>
  );
}

function fmtDate(iso) {
  if (!iso) return "—";
  try {
    return new Date(iso).toLocaleString(undefined, {
      dateStyle: "medium",
      timeStyle: "short",
    });
  } catch {
    return iso;
  }
}

export default function BbqPlansManager() {
  const backendUrl = process.env.REACT_APP_BACKEND_URL;
  const [plans, setPlans] = useState([]);
  const [loading, setLoading] = useState(true);
  const [openId, setOpenId] = useState(null);
  const [filter, setFilter] = useState("all");

  const load = async () => {
    setLoading(true);
    try {
      const { data } = await axios.get(`${backendUrl}/api/bbq-plans`, {
        withCredentials: true
      });
      setPlans(data);
    } catch (error) {
      console.error('Failed to load BBQ plans:', error);
      toast.error('Failed to load BBQ plans');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
  }, []);

  const updateStatus = async (planId, status, note) => {
    try {
      const { data } = await axios.put(
        `${backendUrl}/api/bbq-plans/${planId}`,
        { status, staff_note: note || undefined },
        { withCredentials: true }
      );
      toast.success(note ? "Status & note saved." : "Status updated.");
      setPlans((arr) => arr.map((x) => (x.id === planId ? data : x)));
    } catch (error) {
      console.error('Failed to update BBQ plan:', error);
      toast.error('Failed to update plan');
    }
  };

  const deletePlan = async (planId) => {
    if (!window.confirm("Delete this BBQ plan?")) return;
    try {
      await axios.delete(`${backendUrl}/api/bbq-plans/${planId}`, {
        withCredentials: true
      });
      toast.success("BBQ plan deleted.");
      setPlans((arr) => arr.filter((x) => x.id !== planId));
    } catch (error) {
      console.error('Failed to delete BBQ plan:', error);
      toast.error('Failed to delete plan');
    }
  };

  const visible = filter === "all" ? plans : plans.filter((p) => p.status === filter);

  if (loading) {
    return (
      <div className="text-[#A89F8F] text-sm tracking-[0.2em] uppercase py-12 text-center">
        Loading BBQ Plans...
      </div>
    );
  }

  return (
    <div data-testid="bbq-plans-page">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-end md:justify-between gap-4 mb-10 pb-6 border-b border-[#C8A96A]/15">
        <div>
          <div className="text-[0.65rem] uppercase tracking-[0.32em] text-[#C8A96A] mb-2 flex items-center gap-2">
            <Flame size={12} /> AI BBQ Planner CRM
          </div>
          <h1 className="font-serif text-3xl md:text-4xl text-[#F5F1E8] leading-tight">
            BBQ Plan Leads
          </h1>
          <p className="text-[#A89F8F] text-sm mt-2 max-w-2xl">
            View custom BBQ plans generated by customers, track status, add quotes, and convert leads to bookings.
          </p>
        </div>
        <div className="flex gap-3 flex-wrap">
          <select
            value={filter}
            onChange={(e) => setFilter(e.target.value)}
            className="bg-[#1a1a1a] border border-[#C8A96A]/30 text-[#F5F1E8] text-xs uppercase tracking-[0.18em] px-3 py-2.5"
            data-testid="bbq-plans-filter"
          >
            <option value="all">All ({plans.length})</option>
            {STATUS_OPTIONS.map((s) => (
              <option key={s.id} value={s.id}>
                {s.label}
              </option>
            ))}
          </select>
        </div>
      </div>

      {/* Plans List */}
      {visible.length === 0 ? (
        <div className="border border-dashed border-[#C8A96A]/20 p-12 text-center text-[#A89F8F] text-sm">
          No BBQ plans match this filter.
        </div>
      ) : (
        <div className="space-y-3">
          {visible.map((plan) => (
            <PlanRow
              key={plan.id}
              plan={plan}
              isOpen={openId === plan.id}
              onToggle={() => setOpenId(openId === plan.id ? null : plan.id)}
              onUpdate={(status, note) => updateStatus(plan.id, status, note)}
              onDelete={() => deletePlan(plan.id)}
            />
          ))}
        </div>
      )}
    </div>
  );
}

function PlanRow({ plan, isOpen, onToggle, onUpdate, onDelete }) {
  const [note, setNote] = useState("");
  const [status, setStatus] = useState(plan.status || "new");

  const handleSave = () => {
    onUpdate(status, note);
    setNote("");
  };

  const copyEmail = async () => {
    try {
      await navigator.clipboard.writeText(plan.lead.email);
      toast.success("Email copied to clipboard");
    } catch {
      toast.error("Failed to copy email");
    }
  };

  const copyPlan = async () => {
    try {
      const planText = `
BBQ Plan for ${plan.lead.first_name}
=====================================
People: ${plan.people}
Event Type: ${plan.event_type}
Portion: ${plan.portion_per_person} lbs/person

Selected Proteins: ${plan.selected_categories.join(", ")}

Cuts:
${Object.entries(plan.selected_cuts).map(([cat, cuts]) => `- ${cat}: ${cuts.join(", ")}`).join("\n")}

Beef Quality: ${plan.beef_quality}
Add-ons: ${plan.addons || "None"}

Total: ${plan.total_lbs} lbs
Estimated Price: $${plan.total_price.toFixed(2)}

Contact: ${plan.lead.email}
Zip: ${plan.lead.zip_code}
      `.trim();
      
      await navigator.clipboard.writeText(planText);
      toast.success("Plan details copied to clipboard");
    } catch {
      toast.error("Failed to copy plan details");
    }
  };

  return (
    <div className="bg-[#1a1a1a] border border-[#C8A96A]/15" data-testid={`bbq-plan-${plan.id}`}>
      <button
        onClick={onToggle}
        className="w-full grid grid-cols-12 gap-3 items-center p-4 text-left hover:bg-[#2a2a2a]/30 transition-colors"
      >
        <div className="col-span-12 sm:col-span-3">
          <div className="text-[#F5F1E8] font-medium">{plan.lead.first_name}</div>
          <div className="text-xs text-[#A89F8F]">{plan.lead.email}</div>
        </div>
        <div className="col-span-6 sm:col-span-2 text-sm text-[#F5F1E8] flex items-center gap-1">
          <Users size={14} className="text-[#C8A96A]" />
          {plan.people} people
        </div>
        <div className="col-span-6 sm:col-span-3 text-xs text-[#C8A96A]">
          {plan.event_type}
        </div>
        <div className="col-span-6 sm:col-span-2 text-xs text-[#A89F8F]">
          {fmtDate(plan.created_at)}
        </div>
        <div className="col-span-6 sm:col-span-2 flex items-center justify-end gap-2">
          <div className="text-sm font-semibold text-[#C8A96A]">
            ${plan.total_price.toFixed(0)}
          </div>
          <Badge tone={statusTone(status)}>{status}</Badge>
          <ChevronDown
            size={16}
            className={`text-[#A89F8F] transition-transform ${isOpen ? "rotate-180" : ""}`}
          />
        </div>
      </button>

      {isOpen && (
        <div className="border-t border-[#C8A96A]/15 p-5 space-y-5" data-testid={`bbq-plan-detail-${plan.id}`}>
          {/* Customer Info */}
          <div className="grid md:grid-cols-3 gap-4 text-sm">
            <Detail label="Name" value={plan.lead.first_name} />
            <Detail label="Email" value={plan.lead.email} />
            <Detail label="Zip Code" value={plan.lead.zip_code} />
          </div>

          <div style={{ height: '1px', background: 'linear-gradient(to right, transparent, rgba(200, 169, 106, 0.3), transparent)' }}></div>

          {/* Event Details */}
          <div>
            <div className="text-[0.65rem] uppercase tracking-[0.28em] text-[#C8A96A] mb-3">
              Event Details
            </div>
            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">
              <div className="bg-[#0a0a0a] border border-[#C8A96A]/20 p-4">
                <div className="text-[0.6rem] uppercase tracking-[0.28em] text-[#A89F8F] mb-1">
                  Original Prompt
                </div>
                <div className="text-[#F5F1E8] text-sm italic">"{plan.prompt}"</div>
              </div>
              <div className="bg-[#0a0a0a] border border-[#C8A96A]/20 p-4">
                <div className="text-[0.6rem] uppercase tracking-[0.28em] text-[#A89F8F] mb-1">
                  Guests
                </div>
                <div className="text-[#F5F1E8] text-2xl font-serif">{plan.people}</div>
              </div>
              <div className="bg-[#0a0a0a] border border-[#C8A96A]/20 p-4">
                <div className="text-[0.6rem] uppercase tracking-[0.28em] text-[#A89F8F] mb-1">
                  Event Type
                </div>
                <div className="text-[#C8A96A] text-sm">{plan.event_type}</div>
              </div>
              <div className="bg-[#0a0a0a] border border-[#C8A96A]/20 p-4">
                <div className="text-[0.6rem] uppercase tracking-[0.28em] text-[#A89F8F] mb-1">
                  Per Person
                </div>
                <div className="text-[#F5F1E8] text-sm">{plan.portion_per_person} lbs</div>
              </div>
            </div>
          </div>

          {/* Protein Selection */}
          <div>
            <div className="text-[0.65rem] uppercase tracking-[0.28em] text-[#C8A96A] mb-3">
              Selected Proteins & Cuts
            </div>
            <div className="space-y-3">
              {Object.entries(plan.selected_cuts).map(([category, cuts]) => (
                <div key={category} className="bg-[#0a0a0a] border border-[#C8A96A]/20 p-4">
                  <div className="font-serif text-lg text-[#C8A96A] capitalize mb-2">
                    {category}
                  </div>
                  <div className="flex flex-wrap gap-2">
                    {cuts.map((cut) => (
                      <span
                        key={cut}
                        className="text-xs text-[#F5F1E8] bg-[#1a1a1a] border border-[#C8A96A]/30 px-3 py-1"
                      >
                        {cut}
                      </span>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Beef Quality & Add-ons */}
          <div className="grid md:grid-cols-2 gap-4">
            {plan.selected_categories.includes('steak') && (
              <div>
                <div className="text-[0.6rem] uppercase tracking-[0.28em] text-[#A89F8F] mb-2">
                  Beef Quality Tier
                </div>
                <div className="bg-[#0a0a0a] border border-[#C8A96A]/20 p-3 text-[#F5F1E8] capitalize">
                  {plan.beef_quality.replace('_', ' ')}
                </div>
              </div>
            )}
            {plan.addons && (
              <div>
                <div className="text-[0.6rem] uppercase tracking-[0.28em] text-[#A89F8F] mb-2">
                  Add-ons Requested
                </div>
                <div className="bg-[#0a0a0a] border border-[#C8A96A]/20 p-3 text-[#F5F1E8] whitespace-pre-wrap">
                  {plan.addons}
                </div>
              </div>
            )}
          </div>

          {/* Pricing Summary */}
          <div className="bg-[#0a0a0a] border-l-2 border-[#C8A96A] p-4">
            <div className="flex items-center justify-between">
              <div>
                <div className="text-[0.6rem] uppercase tracking-[0.28em] text-[#A89F8F] mb-1">
                  Total Estimate
                </div>
                <div className="text-sm text-[#F5F1E8]">
                  {plan.total_lbs} lbs total meat
                </div>
              </div>
              <div className="text-right">
                <div className="text-3xl font-serif text-[#C8A96A]">
                  ${plan.total_price.toFixed(2)}
                </div>
                <div className="text-xs text-[#A89F8F]">
                  ${(plan.total_price / plan.people).toFixed(2)} per person
                </div>
              </div>
            </div>
          </div>

          <div style={{ height: '1px', background: 'linear-gradient(to right, transparent, rgba(200, 169, 106, 0.3), transparent)' }}></div>

          {/* Staff Notes History */}
          {plan.staff_messages && plan.staff_messages.length > 0 && (
            <div className="space-y-2">
              <div className="text-[0.65rem] uppercase tracking-[0.28em] text-[#A89F8F]">
                Activity Log
              </div>
              <ul className="space-y-2">
                {plan.staff_messages.map((msg) => (
                  <li key={msg.id} className="bg-[#0a0a0a] border-l-2 border-[#C8A96A]/60 p-3 text-sm">
                    <div className="text-[#F5F1E8] whitespace-pre-wrap">{msg.text}</div>
                    <div className="text-[0.65rem] uppercase tracking-[0.22em] text-[#A89F8F] mt-2">
                      {msg.author} · {fmtDate(msg.created_at)}
                    </div>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Status & Notes Update */}
          <div>
            <div className="text-[0.65rem] uppercase tracking-[0.28em] text-[#C8A96A] mb-3 inline-flex items-center gap-2">
              Update Status / Add Note
            </div>
            <div className="grid md:grid-cols-[1fr_auto] gap-3 items-start">
              <textarea
                value={note}
                onChange={(e) => setNote(e.target.value)}
                placeholder="Add internal note - e.g. 'Contacted customer, sending quote for premium Wagyu upgrade...'"
                rows="3"
                className="w-full bg-[#0a0a0a] border border-[#C8A96A]/25 text-[#F5F1E8] px-4 py-3 focus:outline-none focus:border-[#C8A96A] transition-colors resize-none"
                data-testid={`bbq-plan-note-${plan.id}`}
              />
              <div className="space-y-2">
                <select
                  value={status}
                  onChange={(e) => setStatus(e.target.value)}
                  className="w-full bg-[#0a0a0a] border border-[#C8A96A]/30 text-[#F5F1E8] text-xs uppercase tracking-[0.18em] px-3 py-2.5"
                  data-testid={`bbq-plan-status-${plan.id}`}
                >
                  {STATUS_OPTIONS.map((s) => (
                    <option key={s.id} value={s.id}>
                      {s.label}
                    </option>
                  ))}
                </select>
                <button
                  onClick={handleSave}
                  className="w-full px-4 py-2.5 text-[0.7rem] font-semibold uppercase tracking-wider transition-all"
                  style={{
                    background: 'linear-gradient(135deg, #8B0000, #C8A96A)',
                    color: '#F5F1E8',
                  }}
                  data-testid={`bbq-plan-save-${plan.id}`}
                >
                  Save
                </button>
              </div>
            </div>
          </div>

          {/* Actions */}
          <div className="flex items-center justify-between pt-3 border-t border-[#C8A96A]/15 flex-wrap gap-3">
            <div className="flex gap-3 flex-wrap">
              <button
                onClick={copyEmail}
                className="text-xs uppercase tracking-[0.22em] text-[#C8A96A] hover:underline inline-flex items-center gap-2"
              >
                <Mail size={12} /> Copy Email
              </button>
              <button
                onClick={copyPlan}
                className="text-xs uppercase tracking-[0.22em] text-[#C8A96A] hover:underline inline-flex items-center gap-2"
              >
                <Copy size={12} /> Copy Plan Details
              </button>
            </div>
            <button
              onClick={onDelete}
              className="text-xs uppercase tracking-[0.22em] text-red-400 hover:text-red-300 inline-flex items-center gap-2"
              data-testid={`bbq-plan-delete-${plan.id}`}
            >
              <Trash2 size={12} /> Delete
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

function Detail({ label, value }) {
  return (
    <div>
      <div className="text-[0.6rem] uppercase tracking-[0.28em] text-[#A89F8F] mb-1">{label}</div>
      <div className="text-[#F5F1E8] whitespace-pre-wrap">{value}</div>
    </div>
  );
}
